config/routes.rb
Rails.application.routes.draw do
  root to: 'games#game'
  get 'game', to: 'games#game'
  get 'score', to: 'games#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper

  def game
    @grid = generate_grid(10)
  end

  def score
    @end = Time.now
    @word = params[:word]
    @start = DateTime.parse(params[:start])
    @grid = params[:grid].split("")
    @result = run_game(@word, @grid, @start, @end)
    (session[:games] ||= []).push(@result)
    @games = session[:games]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  require 'open-uri'
  require 'json'

  def all_scores(games_array)
    games_array.collect {|game| game["score"] || game[:score]}.compact
  end

  def avg_score(games_array)
    scores = all_scores(games_array)
    scores.reduce(:+)/scores.length
  end

  def generate_grid(grid_size)
    # TODO: generate random grid of letters
    a = []
    grid_size.times{ a << (65 + rand(25)).chr }
    a
  end

  def run_game(attempt, grid, start_time, end_time)
    # TODO: runs the game and return detailed hash of result
    url = "https://wagon-dictionary.herokuapp.com/#{attempt}"
    duration = (end_time - start_time).to_i
    h = { time: duration, score: 0, message: "Lost! Not in the grid" }
    attempt = attempt.upcase.split("")
    if attempt & grid == attempt
      d = JSON.parse(open(url).read)
      if d["found"]
        score = d["length"].to_i * 20 - duration * 3
        h[:score] = score < 0 ? 0 : score
        h[:message] = "Got it! Well done!"
      else
        h[:message] = "Lost! Not an english word!"
      end
    end
    h
  end

end

app/views/games/game.html.erb
<% @start = Time.now  %>
<div class="container d-flex justify-content-center" style="height: 100vh">
  <div class="my-auto bg-primary p-5 w-75 text-center">
    <h1 class="text-white">Play a game!</h1>
    <div>
      <ul class="text-white list-inline my-5">
        <% @grid.each do |l|  %>
        <li class="list-inline-item bg-light text-primary p-3 m-1"><%= l %></li>
        <% end %>
      </ul>
    </div>
    <div class="">
      <form action="/score" class="form-inline my-5 mx-auto w-75">
      <%= hidden_field_tag :start, @start %>
      <%= hidden_field_tag :grid, @grid %>
      <input placeholder="your word..." type="text" name="word" class="form-control w-75">
      <input type="submit" class="btn btn-light w-25">
    </form>
    </div>

  </div>
</div>

app/views/games/score.html.erb
<div class="container d-flex justify-content-center" style="height: 100vh">
  <div class="my-auto bg-primary p-5 w-75 text-center">
    <div>
      <h1 class="text-white"><%= @result[:message] %></h1>
      <div class="my-5 list-inline">
        <div class="bg-light p-5 m-1 list-inline-item">
          <p class="text-secondary">word</p>
          <h2 class="text-primary"><%= @word %></h2>
        </div>
        <div class="bg-light p-5 m-1 list-inline-item">
          <p class="text-secondary">time</p>
          <h2 class="text-primary"><%= @result[:time] %></h2>
        </div>
        <div class="bg-light p-5 m-1 list-inline-item">
          <p class="text-secondary">score</p>
          <h2 class="text-primary"><%= @result[:score] %></h2>
        </div>
      </div>
      <%= link_to "Play again!", game_path, class: "btn btn-light w-50 my-auto" %>
    </div>
    <div class="bg-light d-flex my-3">
      <div class="border border-primary p-2 m-3">
        <p class="text-secondary">average score</p>
        <h2 class="text-primary"><%= avg_score(@games) %></h2>
      </div>
      <p class="text-secondary align-self-center">all scores</p>
      <ul class="list-inline">
        <% all_scores(@games).each do |score| %>
          <li class="list-inline-item my-1 mx-2"> - <%= score %> - </li>
        <% end  %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>